<?php

namespace App\Constants;

class WebSocketMutations
{
    const SOCK_NEW_MESSAGE = 'SOCK_NEW_MESSAGE';
    const SOCK_REMOVE_MESSAGE = 'SOCK_REMOVE_MESSAGE';
    const SOCK_PIN_MESSAGE = 'SOCK_PIN_MESSAGE';
    const SOCK_UNPIN_MESSAGE = 'SOCK_UNPIN_MESSAGE';
    const SOCK_SET_CHAT_CONFIG = 'SOCK_SET_CHAT_CONFIG';
    const SOCK_SET_MESSAGE_ANSWERED = 'SOCK_SET_MESSAGE_ANSWERED';
    const SOCK_SET_MESSAGE_MODERATION = 'SOCK_SET_MESSAGE_MODERATION';
    const SOCK_SET_MESSAGE_LIKE = 'SOCK_SET_MESSAGE_LIKE';
    const SOCK_MOVE_MESSAGE = 'SOCK_MOVE_MESSAGE';
    const SOCK_BAN_USER = 'SOCK_BAN_USER';
    const SOCK_UNBAN_USER = 'SOCK_UNBAN_USER';
    const SOCK_SET_STREAM_STATS = 'SOCK_SET_STREAM_STATS';
    const SOCK_USER_VERIFIED = 'SOCK_USER_VERIFIED';
    const SOCK_POLL_NEW = 'SOCK_POLL_NEW';
    const SOCK_EDIT_POLL = 'SOCK_EDIT_POLL';
    const SOCK_UPDATE_POLL_STYLE = 'SOCK_UPDATE_POLL_STYLE';
    const SOCK_NEW_SALE = 'SOCK_NEW_SALE';
    const SOCK_EDIT_SALE = 'SOCK_EDIT_SALE';
    const SOCK_SORT_SALES = 'SOCK_SORT_SALES';
    const SOCK_DELETE_SALE = 'SOCK_DELETE_SALE';
    const SOCK_SHARE_SALE = 'SOCK_SHARE_SALE';
    const SOCK_DONE_SALE = 'SOCK_DONE_SALE';
    const SOCK_CLICK_SALE = 'SOCK_CLICK_SALE';
    const SOCK_UPDATE_POLL = 'SOCK_UPDATE_POLL';
    const SOCK_POLL_SHARE = 'SOCK_POLL_SHARE';
    const SOCK_POLL_HIDE = 'SOCK_POLL_HIDE';
    const SOCK_POLL_SHOW = 'SOCK_POLL_SHOW';
    const SOCK_POLL_CLOSE = 'SOCK_POLL_CLOSE';
    const SOCK_POLL_DELETE = 'SOCK_POLL_DELETE';
    const SOCK_UPDATE_BALANCE = 'SOCK_UPDATE_BALANCE';
    const SOCK_REDIRECT_USERS = 'SOCK_REDIRECT_USERS';
    const SOCK_REMOVE_MEMBER_ROLE = 'SOCK_REMOVE_MEMBER_ROLE';
    const SOCK_KICK_USER = 'SOCK_KICK_USER';
    const SOCK_SESSION_STREAM_ONAIR = 'SOCK_SESSION_STREAM_ONAIR';
    const SOCK_FILE_EXPORT = 'SOCK_FILE_EXPORT';
}
